use_frameworks!

target 'DagoTracked_Example' do
  pod 'DagoTracked', :path => '../../'

  target 'DagoTracked_Tests' do
    inherit! :search_paths

    
  end
end

target 'DagoTracked_tvOS_Example' do
  pod 'DagoTracked', :path => '../../'
end
