use_frameworks!

target 'DagoConstrained_Example' do
  pod 'DagoConstrained', :path => '../../'
  pod 'DagoTracked', :path => '../../'

  pod "RxGesture"
  
  target 'DagoConstrained_Tests' do
    inherit! :search_paths

    
  end
end
